/*
 * This source file was generated by the Gradle 'init' task
 */
package ir.nas;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;
import ir.nas.model.Author;
import ir.nas.model.Book;
import ir.nas.model.Profile;
import ir.nas.model.Publisher;
import ir.nas.model.embeddable.Address;
import ir.nas.repository.author.AuthorRepositoryImpl;
import ir.nas.repository.book.BookRepositoryImpl;
import ir.nas.repository.profile.ProfileRepositoryImpl;
import ir.nas.repository.publisher.PublisherRepositoryImpl;
import ir.nas.service.AuthorService;
import ir.nas.service.BookService;
import ir.nas.service.ProfileService;
import ir.nas.service.PublisherService;
import ir.nas.util.ColorCMD;

public class App
{
    public static void main(String[] args)
    {
        // 0. Cofigs
        Examples examples = new Examples();

        // o Book
        BookRepositoryImpl bookRepositoryImpl = new BookRepositoryImpl();
        BookService bookService = new BookService(bookRepositoryImpl);

        // o Author
        AuthorRepositoryImpl authorRepositoryImpl = new AuthorRepositoryImpl();
        AuthorService authorService = new AuthorService(authorRepositoryImpl);

        // o Profile
        ProfileRepositoryImpl profileRepositoryImpl = new ProfileRepositoryImpl();
        ProfileService profileService = new ProfileService(profileRepositoryImpl);

        // o Publisher
        PublisherRepositoryImpl publisherRepositoryImpl = new PublisherRepositoryImpl();
        PublisherService publisherService = new PublisherService(publisherRepositoryImpl);

        // ------------------------------------------------------------------------------------------
        // 1. Create the required entities:
        //      o At least 3 authors
        //      o Their profiles
        //      o 2 publisher
        //      o 4 books
        // ------------------------------------------------------------------------------------------
        Address address1 = examples.addressTehran;
        Address address2 = examples.addressIsfahan;
        Address address3 = examples.addressMashhad;
        Address address4 = examples.addressValiasr;
        Address address5 = examples.addressMotehari;

        Author ali = examples.author1;
        Author sara = examples.author2;
        Author mohammad = examples.author3;

        Profile aliProfile = examples.profile1;
        Profile saraProfile = examples.profile2;
        Profile mohammadProfile = examples.profile3;

        Publisher publisher = examples.publisher1;
        Publisher publisher2 = examples.publisher2;

        Book book1 = examples.book1;
        Book book2 = examples.book2;
        Book book3 = examples.book3;
        Book book4 = examples.book4;

        // 2. Establish the required relationships

        // ------------------------------------------------------------------------------------------
        // 3. Persist all objects into the database--------------------------------------------------
        // ------------------------------------------------------------------------------------------
        System.out.println(ColorCMD.log("3. Persist all objects into the database"));

        // Book
        bookService.addBook(book1);
        bookService.addBook(book2);
        bookService.addBook(book3);
        bookService.addBook(book4);
        System.out.println(ColorCMD.log("Books Added."));

        // Author
        authorService.addAuthor(ali);
        authorService.addAuthor(sara);
        authorService.addAuthor(mohammad);
        System.out.println(ColorCMD.log("Authors Added."));

        // Publisher
        publisherService.addPublisher(publisher);
        publisherService.addPublisher(publisher2);
        System.out.println(ColorCMD.log("Publisher Added."));

        // Profile
        profileService.addProfile(aliProfile);
        profileService.addProfile(saraProfile);
        profileService.addProfile(mohammadProfile);
        System.out.println(ColorCMD.log("Profile Added."));

        // ------------------------------------------------------------------------------------------
        // UPDATE REALEATIONSHIPS--------------------------------------------------------------------
        // ------------------------------------------------------------------------------------------
        // Profiles
        aliProfile.setAuthor(ali);
        saraProfile.setAuthor(sara);
        mohammadProfile.setAuthor(mohammad);

        // Authors-Address
        ali.setAddress(address1);
        sara.setAddress(address2);
        mohammad.setAddress(address3);

        // Authors-Profile
        ali.setProfile(aliProfile);
        sara.setProfile(saraProfile);
        mohammad.setProfile(mohammadProfile);

        // Authors-Books
        ali.setBooks(Arrays.asList(book1, book3));
        sara.setBooks(Arrays.asList(book1, book3, book4));
        mohammad.setBooks(Arrays.asList(book1, book2));

        // Authors-Publisher
        ali.setPublisher(publisher);
        sara.setPublisher(publisher2);
        mohammad.setPublisher(publisher2);

        // Books-Authors
        book1.setAuthors(Arrays.asList(ali, sara, mohammad));
        book2.setAuthors(Arrays.asList(mohammad));
        book3.setAuthors(Arrays.asList(ali, sara));
        book4.setAuthors(Arrays.asList(sara));

        // Books-Publisher
        book1.setPublisher(publisher);
        book2.setPublisher(publisher);
        book3.setPublisher(publisher2);
        book4.setPublisher(publisher2);

        // Publisher-Address
        publisher.setAddress(address4);
        publisher2.setAddress(address5);

        // Publisher-Authors
        publisher.setAuthors(Arrays.asList(ali));
        publisher2.setAuthors(Arrays.asList(sara, mohammad));

        // Publisher-Books
        publisher.setBooks(Arrays.asList(book1, book2));
        publisher2.setBooks(Arrays.asList(book3, book4));

        // UPDATES-----------------------------------------------------------------------------------
        bookService.updateBook(book1);
        bookService.updateBook(book2);
        bookService.updateBook(book3);
        bookService.updateBook(book4);

        authorService.updateAuthor(ali);
        authorService.updateAuthor(sara);
        authorService.updateAuthor(mohammad);

        profileService.updateProfile(aliProfile);
        profileService.updateProfile(saraProfile);
        profileService.updateProfile(mohammadProfile);

        publisherService.updatePublisher(publisher);
        publisherService.updatePublisher(publisher2);

        // ------------------------------------------------------------------------------------------
        // 4. Retrieve one book by its ID------------------------------------------------------------
        // ------------------------------------------------------------------------------------------
        Book findedBook = bookService.findBookById(0L);
        System.out.println(ColorCMD.log("4. Retrieve one book by its ID: [ID 0]" + findedBook));

        // ------------------------------------------------------------------------------------------
        // 5. Update some information of the retrieved book (for example: change its price)----------
        // ------------------------------------------------------------------------------------------
        findedBook.setPrice(new BigDecimal(2.0));
        System.out.println(ColorCMD.log("""
                5. Update some information of the retrieved book (for example: change its price)
                [ID 0 -> price: $2.0]
                """));

        // ------------------------------------------------------------------------------------------
        // 6. Save the changes-----------------------------------------------------------------------
        // ------------------------------------------------------------------------------------------
        bookService.updateBook(findedBook);
        System.out.println(ColorCMD.log("6. Save the changes"));
        Book findedUpdateBook = bookService.findBookById(0L);
        System.out.println(ColorCMD.log(findedUpdateBook.toString()));

        // ------------------------------------------------------------------------------------------
        // 7. Delete one book------------------------------------------------------------------------
        // ------------------------------------------------------------------------------------------
        bookService.deleteBook(0L);
        System.out.println(ColorCMD.log("7. Delete one book: [ID 0]"));

        // ------------------------------------------------------------------------------------------
        // 8. Display the created objects and their relationships (for example: print to console)----
        // ------------------------------------------------------------------------------------------
        System.out.println(ColorCMD.log("""
                8. Display the created objects and their relationships (for example: print to console)
                """));

        List<Book> allBook = bookService.findAllBook();
        System.out.println(allBook);
        // ------------------------------------------------------------------------------------------
        // 9. Verify the final database state (by querying and showing results)----------------------
        // ------------------------------------------------------------------------------------------
    }
}
